title: BL2/TPS SDK Mod Database
description: >-
  SDK mods for Borderlands 2, The Pre-Sequel, and the Attack on Dragon Keep standalone.

color_scheme: willow2

collections:
  willow2_mods:
    sort-by: title
    permalink: /willow2-mod-db/mods/:name/
    output: true

just_the_docs:
  collections:
    willow2_mods:
      name: Mods

nav_external_links:
  - title: Modding Support Discord
    url: https://discord.gg/bXeqV8Ef9R
  - title: Latest Release
    url: https://github.com/bl-sdk/willow2-mod-manager/releases/latest

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

  - Readme.md

  - developing
  - oak-mod-db
  - willow1-mod-db
