title: BL1 SDK Mod Database
description: >-
  SDK mods for Borderlands 1.

color_scheme: willow1

collections:
  willow1_mods:
    sort-by: title
    permalink: /willow1-mod-db/mods/:name/
    output: true

just_the_docs:
  collections:
    willow1_mods:
      name: Mods

nav_external_links:
  - title: Modding Support Discord
    url: https://discord.gg/bXeqV8Ef9R
  - title: Latest Release
    url: https://github.com/bl-sdk/willow1-mod-manager/releases/latest

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

  - Readme.md

  - developing
  - oak-mod-db
  - willow2-mod-db
